using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MeowDSIO.DataTypes.MSB.EVENT_PARAM_ST
{
    public class MsbEventGenerator : MsbEventBase
    {
        public short SUx00 { get; set; } = 0;
        public short SUx02 { get; set; } = 0;
        public short SUx04 { get; set; } = 0;
        public short SUx06 { get; set; } = 0;
        public float SUx08 { get; set; } = 0;
        public float SUx0C { get; set; } = 0;
        public int SUx10 { get; set; } = 0;
        public int SUx14 { get; set; } = 0;
        public int SUx18 { get; set; } = 0;
        public int SUx1C { get; set; } = 0;
        public int SUx20 { get; set; } = 0;
        public int SUx24 { get; set; } = 0;
        public int SUx28 { get; set; } = 0;
        public int SUx2C { get; set; } = 0;
        public int RegionIndex2 { get; set; } = 0;
        public int SUx34 { get; set; } = 0;
        public int SUx38 { get; set; } = 0;
        public int SUx3C { get; set; } = 0;
        public int PartIndex2 { get; set; } = 0;
        public int PartIndex3 { get; set; } = 0;
        public int SUx48 { get; set; } = 0;
        public int SUx4C { get; set; } = 0;
        public int SUx50 { get; set; } = 0;
        public int SUx54 { get; set; } = 0;
        public int SUx58 { get; set; } = 0;
        public int SUx5C { get; set; } = 0;
        public int SUx60 { get; set; } = 0;
        public int SUx64 { get; set; } = 0;
        public int SUx68 { get; set; } = 0;
        public int SUx6C { get; set; } = 0;
        public int SUx70 { get; set; } = 0;
        public int SUx74 { get; set; } = 0;
        public int SUx78 { get; set; } = 0;
        public int SUx7C { get; set; } = 0;
        public int SUx80 { get; set; } = 0;
        public int SUx84 { get; set; } = 0;
        public int SUx88 { get; set; } = 0;
        public int SUx8C { get; set; } = 0;
        public int SUx90 { get; set; } = 0;
        public int SUx94 { get; set; } = 0;
        public int SUx98 { get; set; } = 0;
        public int SUx9C { get; set; } = 0;
        public int SUxA0 { get; set; } = 0;
        public int SUxA4 { get; set; } = 0;
        public int SUxA8 { get; set; } = 0;
        public int SUxAC { get; set; } = 0;
        public int SUxB0 { get; set; } = 0;
        public int SUxB4 { get; set; } = 0;
        public int SUxB8 { get; set; } = 0;
        public int SUxBC { get; set; } = 0;
        public int SUxC0 { get; set; } = 0;
        public int SUxC4 { get; set; } = 0;
        public int SUxC8 { get; set; } = 0;
        public int SUxCC { get; set; } = 0;
        public int SUxD0 { get; set; } = 0;
        public int SUxD4 { get; set; } = 0;
        public int SUxD8 { get; set; } = 0;
        public int SUxDC { get; set; } = 0;
        public int SUxE0 { get; set; } = 0;
        public int SUxE4 { get; set; } = 0;
        public int SUxE8 { get; set; } = 0;
        public int SUxEC { get; set; } = 0;
        public int SUxF0 { get; set; } = 0;
        public int SUxF4 { get; set; } = 0;
        public int SUxF8 { get; set; } = 0;
        public int SUxFC { get; set; } = 0;

        protected override EventParamSubtype GetSubtypeValue()
        {
            return EventParamSubtype.Generators;
        }

        protected override void SubtypeRead(DSBinaryReader bin)
        {
            SUx00 = bin.ReadInt16();
            SUx02 = bin.ReadInt16();
            SUx04 = bin.ReadInt16();
            SUx06 = bin.ReadInt16();
            SUx08 = bin.ReadSingle();
            SUx0C = bin.ReadSingle();
            SUx10 = bin.ReadInt32();
            SUx14 = bin.ReadInt32();
            SUx18 = bin.ReadInt32();
            SUx1C = bin.ReadInt32();
            SUx20 = bin.ReadInt32();
            SUx24 = bin.ReadInt32();
            SUx28 = bin.ReadInt32();
            SUx2C = bin.ReadInt32();
            RegionIndex2 = bin.ReadInt32();
            SUx34 = bin.ReadInt32();
            SUx38 = bin.ReadInt32();
            SUx3C = bin.ReadInt32();
            PartIndex2 = bin.ReadInt32();
            PartIndex3 = bin.ReadInt32();
            SUx48 = bin.ReadInt32();
            SUx4C = bin.ReadInt32();
            SUx50 = bin.ReadInt32();
            SUx54 = bin.ReadInt32();
            SUx58 = bin.ReadInt32();
            SUx5C = bin.ReadInt32();
            SUx60 = bin.ReadInt32();
            SUx64 = bin.ReadInt32();
            SUx68 = bin.ReadInt32();
            SUx6C = bin.ReadInt32();
            SUx70 = bin.ReadInt32();
            SUx74 = bin.ReadInt32();
            SUx78 = bin.ReadInt32();
            SUx7C = bin.ReadInt32();
            SUx80 = bin.ReadInt32();
            SUx84 = bin.ReadInt32();
            SUx88 = bin.ReadInt32();
            SUx8C = bin.ReadInt32();
            SUx90 = bin.ReadInt32();
            SUx94 = bin.ReadInt32();
            SUx98 = bin.ReadInt32();
            SUx9C = bin.ReadInt32();
            SUxA0 = bin.ReadInt32();
            SUxA4 = bin.ReadInt32();
            SUxA8 = bin.ReadInt32();
            SUxAC = bin.ReadInt32();
            SUxB0 = bin.ReadInt32();
            SUxB4 = bin.ReadInt32();
            SUxB8 = bin.ReadInt32();
            SUxBC = bin.ReadInt32();
            SUxC0 = bin.ReadInt32();
            SUxC4 = bin.ReadInt32();
            SUxC8 = bin.ReadInt32();
            SUxCC = bin.ReadInt32();
            SUxD0 = bin.ReadInt32();
            SUxD4 = bin.ReadInt32();
            SUxD8 = bin.ReadInt32();
            SUxDC = bin.ReadInt32();
            SUxE0 = bin.ReadInt32();
            SUxE4 = bin.ReadInt32();
            SUxE8 = bin.ReadInt32();
            SUxEC = bin.ReadInt32();
            SUxF0 = bin.ReadInt32();
            SUxF4 = bin.ReadInt32();
            SUxF8 = bin.ReadInt32();
            SUxFC = bin.ReadInt32();
        }

        protected override void SubtypeWrite(DSBinaryWriter bin)
        {
            bin.Write(SUx00);
            bin.Write(SUx02);
            bin.Write(SUx04);
            bin.Write(SUx06);
            bin.Write(SUx08);
            bin.Write(SUx0C);
            bin.Write(SUx10);
            bin.Write(SUx14);
            bin.Write(SUx18);
            bin.Write(SUx1C);
            bin.Write(SUx20);
            bin.Write(SUx24);
            bin.Write(SUx28);
            bin.Write(SUx2C);
            bin.Write(RegionIndex2);
            bin.Write(SUx34);
            bin.Write(SUx38);
            bin.Write(SUx3C);
            bin.Write(PartIndex2);
            bin.Write(PartIndex3);
            bin.Write(SUx48);
            bin.Write(SUx4C);
            bin.Write(SUx50);
            bin.Write(SUx54);
            bin.Write(SUx58);
            bin.Write(SUx5C);
            bin.Write(SUx60);
            bin.Write(SUx64);
            bin.Write(SUx68);
            bin.Write(SUx6C);
            bin.Write(SUx70);
            bin.Write(SUx74);
            bin.Write(SUx78);
            bin.Write(SUx7C);
            bin.Write(SUx80);
            bin.Write(SUx84);
            bin.Write(SUx88);
            bin.Write(SUx8C);
            bin.Write(SUx90);
            bin.Write(SUx94);
            bin.Write(SUx98);
            bin.Write(SUx9C);
            bin.Write(SUxA0);
            bin.Write(SUxA4);
            bin.Write(SUxA8);
            bin.Write(SUxAC);
            bin.Write(SUxB0);
            bin.Write(SUxB4);
            bin.Write(SUxB8);
            bin.Write(SUxBC);
            bin.Write(SUxC0);
            bin.Write(SUxC4);
            bin.Write(SUxC8);
            bin.Write(SUxCC);
            bin.Write(SUxD0);
            bin.Write(SUxD4);
            bin.Write(SUxD8);
            bin.Write(SUxDC);
            bin.Write(SUxE0);
            bin.Write(SUxE4);
            bin.Write(SUxE8);
            bin.Write(SUxEC);
            bin.Write(SUxF0);
            bin.Write(SUxF4);
            bin.Write(SUxF8);
            bin.Write(SUxFC);
        }
    }
}
